package fr.siovision.voyages.domain.model;

public enum TypeDocument {
    PERMIS_DE_CONDUIRE,
    CARTE_D_IDENTITE,
    PASSEPORT,
    CARTE_VITALE,
    ATTESTATION_ASSURANCE,
    CARTE_EUROPEENNE_ASSURANCE_MALADIE,
    VISA,
    AUTORISATION_SORTIE_TERRITOIRE,
    ORDONNANCE,
    CERTIFICAT_MEDICAL,
    AUTORISATION_PRELEVEMENT,
    AUTRE
}
