INSERT INTO public.section (id, description, libelle) VALUES (1, '2ème année de BTS Communication', '2TS CE');
INSERT INTO public.section (id, description, libelle) VALUES (2, '2ème année de BTS Comptabilité et Gestion', '2TS CG');
INSERT INTO public.section (id, description, libelle) VALUES (3, '2ème année de BTS Services Informatiques aux Organisations', '2TS SIO');
INSERT INTO public.section (id, description, libelle) VALUES (4, '2ème année de BTS Management Commercial Opérationnel', '2TS MCO');
INSERT INTO public.section (id, description, libelle) VALUES (5, '2ème année de BTS Services et Prestations des Secteurs Sanitaire et Social', '2TS 3S');
INSERT INTO public.section (id, description, libelle) VALUES (6, '2ème année de BTS Electrotechnique', '2TS ET');
INSERT INTO public.section (id, description, libelle) VALUES (7, '2ème année de BTS Cybersécurité Informatique et Réseaux Électronique option Réseaux', '2TS CIEL');
INSERT INTO public.section (id, description, libelle) VALUES (8, '2ème année de BTS Conception et Réalisation de Systèmes Automatiques', '2TS SA');
INSERT INTO public.section (id, description, libelle) VALUES (9, '1ère année de BTS Communication', '1TS CE');
INSERT INTO public.section (id, description, libelle) VALUES (10, '1ère année de BTS Comptabilité et Gestion', '1TS CG');
INSERT INTO public.section (id, description, libelle) VALUES (11, '1ère année de BTS Services Informatiques aux Organisations', '1TS SIO');
INSERT INTO public.section (id, description, libelle) VALUES (12, '1ère année de BTS Management Commercial Opérationnel', '1TS MCO');
INSERT INTO public.section (id, description, libelle) VALUES (13, '1ère année de BTS Services et Prestations des Secteurs Sanitaire et Social', '1TS 3S');
INSERT INTO public.section (id, description, libelle) VALUES (14, '1ère année de BTS Electrotechnique', '1TS ET');
INSERT INTO public.section (id, description, libelle) VALUES (15, '1ère année de BTS Cybersécurité Informatique et Réseaux Électronique option Réseaux', '1TS CIEL');
INSERT INTO public.section (id, description, libelle) VALUES (16, '1ère année de BTS Conception et Réalisation de Systèmes Automatiques', '1TS SA');
INSERT INTO public.section (id, description, libelle) VALUES (17, 'Terminale Professionnelle Accompagnement Soins et Services à la Personne', 'TASSP');
INSERT INTO public.section (id, description, libelle) VALUES (18, 'Terminale Professionnelle Métiers de l’Electricité et de ses Environnements Connectés', 'TMELEC');
INSERT INTO public.section (id, description, libelle) VALUES (19, 'Terminale Professionnelle Maintenance des Equipements Industriels', 'TMEI');
INSERT INTO public.section (id, description, libelle) VALUES (20, 'Terminale Professionnelle Accueil Relations Clients Usagers', 'TARC');
INSERT INTO public.section (id, description, libelle) VALUES (21, 'Terminale Professionnelle Commerce', 'TCOM');
INSERT INTO public.section (id, description, libelle) VALUES (22, 'Première Professionnelle Accompagnement Soins et Services à la Personne', '1ASSP');
INSERT INTO public.section (id, description, libelle) VALUES (23, 'Première Professionnelle Métiers de l’Electricité et de ses Environnements Connectés', '1MELEC');
INSERT INTO public.section (id, description, libelle) VALUES (24, 'Première Professionnelle Maintenance des Equipements Industriels', '1MEI');
INSERT INTO public.section (id, description, libelle) VALUES (25, 'Première Professionnelle Métiers de l’Accueil', '1ARC');
INSERT INTO public.section (id, description, libelle) VALUES (26, 'Première Professionnelle Métiers du Commerce et de la Vente option A : Gestion et Animation de l’Espace Commercial', '1COM');
INSERT INTO public.section (id, description, libelle) VALUES (27, 'Seconde Professionnelle Accompagnement Soins et Services à la Personne', '2ASSP');
INSERT INTO public.section (id, description, libelle) VALUES (28, 'Seconde Professionnelle Métiers de l’Electricité et de ses Environnements Connectés', '2MELEC');
INSERT INTO public.section (id, description, libelle) VALUES (29, 'Seconde Professionnelle Maintenance des Equipements Industriels', '2MEI');
INSERT INTO public.section (id, description, libelle) VALUES (30, 'Seconde Professionnelle Métiers Relations Clients commune', '2MRC');
INSERT INTO public.section (id, description, libelle) VALUES (31, 'Troisième Prépa Métiers', '3PMET');
INSERT INTO public.section (id, description, libelle) VALUES (32, 'Terminale Générale – division1', 'TGA');
INSERT INTO public.section (id, description, libelle) VALUES (33, 'Terminale Générale – division2', 'TGB');
INSERT INTO public.section (id, description, libelle) VALUES (34, 'Terminale STI Développement Durable -Energie et Environnement(A)', 'TI2DA-EE');
INSERT INTO public.section (id, description, libelle) VALUES (35, 'Terminale STI Développement Durable - Innovation Technologique et Eco-Conception(B)', 'TI2DB-ITEC');
INSERT INTO public.section (id, description, libelle) VALUES (36, 'Terminale STI Développement Durable - Système d’Information et Numérique(C)', 'TI2DC-SIN');
INSERT INTO public.section (id, description, libelle) VALUES (37, 'Terminale Sciences et Technologies de la Santé et du Social -division 1', 'TSSS1');
INSERT INTO public.section (id, description, libelle) VALUES (38, 'Terminale Sciences et Technologies de la Santé et du Social -division 2', 'TSSS2');
INSERT INTO public.section (id, description, libelle) VALUES (39, 'Terminale STMG spécialité Ressources Humaines', 'TRH');
INSERT INTO public.section (id, description, libelle) VALUES (40, 'Terminale STMG spécialité Gestion et Finance', 'TGF');
INSERT INTO public.section (id, description, libelle) VALUES (41, 'Terminale STMG spécialité Mercatique (marketing)', 'TMC');
INSERT INTO public.section (id, description, libelle) VALUES (42, 'Première Générale – division1', '1GA');
INSERT INTO public.section (id, description, libelle) VALUES (43, 'Première Générale – division2', '1GB');
INSERT INTO public.section (id, description, libelle) VALUES (44, 'Première STI Développement Durable– division1', '1I2DA');
INSERT INTO public.section (id, description, libelle) VALUES (45, 'Première STI Développement Durable– division2', '1I2DB');
INSERT INTO public.section (id, description, libelle) VALUES (46, 'Première Sciences et Technologies de la Santé et du Social– division1', '1SSS1');
INSERT INTO public.section (id, description, libelle) VALUES (47, 'Première Sciences et Technologies de la Santé et du Social– division2', '1SSS2');
INSERT INTO public.section (id, description, libelle) VALUES (48, 'Première Sciences et Techniques du Management et de la Gestion-division 1', '1SG1');
INSERT INTO public.section (id, description, libelle) VALUES (49, 'Première Sciences et Techniques du Management et de la Gestion-division 2', '1SG2');
INSERT INTO public.section (id, description, libelle) VALUES (50, 'Seconde Générale et Technologique - division 1', '2GT1');
INSERT INTO public.section (id, description, libelle) VALUES (51, 'Seconde Générale et Technologique - division 2', '2GT2');
INSERT INTO public.section (id, description, libelle) VALUES (52, 'Seconde Générale et Technologique - division 3', '2GT3');
INSERT INTO public.section (id, description, libelle) VALUES (53, 'Seconde Générale et Technologique - division 4', '2GT4');
INSERT INTO public.section (id, description, libelle) VALUES (54, 'Seconde Générale et Technologique - division 5', '2GT5');
INSERT INTO public.section (id, description, libelle) VALUES (55, 'Classe Préparatoire des Métiers Sécurité Intérieure', 'PCMSI');
