INSERT INTO public.section (id, public_id, description, label) VALUES (1, gen_random_uuid(), '2ème année de BTS Communication', '2TS CE');
INSERT INTO public.section (id, public_id, description, label) VALUES (2,gen_random_uuid(),  '2ème année de BTS Comptabilité et Gestion', '2TS CG');
INSERT INTO public.section (id, public_id, description, label) VALUES (3,gen_random_uuid(),  '2ème année de BTS Services Informatiques aux Organisations', '2TS SIO');
INSERT INTO public.section (id, public_id, description, label) VALUES (4,gen_random_uuid(),  '2ème année de BTS Management Commercial Opérationnel', '2TS MCO');
INSERT INTO public.section (id, public_id, description, label) VALUES (5,gen_random_uuid(),  '2ème année de BTS Services et Prestations des Secteurs Sanitaire et Social', '2TS 3S');
INSERT INTO public.section (id, public_id, description, label) VALUES (6,gen_random_uuid(),  '2ème année de BTS Electrotechnique', '2TS ET');
INSERT INTO public.section (id, public_id, description, label) VALUES (7,gen_random_uuid(),  '2ème année de BTS Cybersécurité Informatique et Réseaux Électronique option Réseaux', '2TS CIEL');
INSERT INTO public.section (id, public_id, description, label) VALUES (8,gen_random_uuid(),  '2ème année de BTS Conception et Réalisation de Systèmes Automatiques', '2TS SA');
INSERT INTO public.section (id, public_id, description, label) VALUES (9,gen_random_uuid(),  '1ère année de BTS Communication', '1TS CE');
INSERT INTO public.section (id, public_id, description, label) VALUES (10,gen_random_uuid(),  '1ère année de BTS Comptabilité et Gestion', '1TS CG');
INSERT INTO public.section (id, public_id, description, label) VALUES (11,gen_random_uuid(),  '1ère année de BTS Services Informatiques aux Organisations', '1TS SIO');
INSERT INTO public.section (id, public_id, description, label) VALUES (12,gen_random_uuid(),  '1ère année de BTS Management Commercial Opérationnel', '1TS MCO');
INSERT INTO public.section (id, public_id, description, label) VALUES (13,gen_random_uuid(),  '1ère année de BTS Services et Prestations des Secteurs Sanitaire et Social', '1TS 3S');
INSERT INTO public.section (id, public_id, description, label) VALUES (14,gen_random_uuid(),  '1ère année de BTS Electrotechnique', '1TS ET');
INSERT INTO public.section (id, public_id, description, label) VALUES (15,gen_random_uuid(),  '1ère année de BTS Cybersécurité Informatique et Réseaux Électronique option Réseaux', '1TS CIEL');
INSERT INTO public.section (id, public_id, description, label) VALUES (16,gen_random_uuid(),  '1ère année de BTS Conception et Réalisation de Systèmes Automatiques', '1TS SA');
INSERT INTO public.section (id, public_id, description, label) VALUES (17,gen_random_uuid(),  'Terminale Professionnelle Accompagnement Soins et Services à la Personne', 'TASSP');
INSERT INTO public.section (id, public_id, description, label) VALUES (18,gen_random_uuid(),  'Terminale Professionnelle Métiers de l’Electricité et de ses Environnements Connectés', 'TMELEC');
INSERT INTO public.section (id, public_id, description, label) VALUES (19,gen_random_uuid(),  'Terminale Professionnelle Maintenance des Equipements Industriels', 'TMEI');
INSERT INTO public.section (id, public_id, description, label) VALUES (20,gen_random_uuid(),  'Terminale Professionnelle Accueil Relations Clients Usagers', 'TARC');
INSERT INTO public.section (id, public_id, description, label) VALUES (21,gen_random_uuid(),  'Terminale Professionnelle Commerce', 'TCOM');
INSERT INTO public.section (id, public_id, description, label) VALUES (22,gen_random_uuid(),  'Première Professionnelle Accompagnement Soins et Services à la Personne', '1ASSP');
INSERT INTO public.section (id, public_id, description, label) VALUES (23,gen_random_uuid(),  'Première Professionnelle Métiers de l’Electricité et de ses Environnements Connectés', '1MELEC');
INSERT INTO public.section (id, public_id, description, label) VALUES (24,gen_random_uuid(),  'Première Professionnelle Maintenance des Equipements Industriels', '1MEI');
INSERT INTO public.section (id, public_id, description, label) VALUES (25,gen_random_uuid(),  'Première Professionnelle Métiers de l’Accueil', '1ARC');
INSERT INTO public.section (id, public_id, description, label) VALUES (26,gen_random_uuid(),  'Première Professionnelle Métiers du Commerce et de la Vente option A : Gestion et Animation de l’Espace Commercial', '1COM');
INSERT INTO public.section (id, public_id, description, label) VALUES (27,gen_random_uuid(),  'Seconde Professionnelle Accompagnement Soins et Services à la Personne', '2ASSP');
INSERT INTO public.section (id, public_id, description, label) VALUES (28,gen_random_uuid(),  'Seconde Professionnelle Métiers de l’Electricité et de ses Environnements Connectés', '2MELEC');
INSERT INTO public.section (id, public_id, description, label) VALUES (29,gen_random_uuid(),  'Seconde Professionnelle Maintenance des Equipements Industriels', '2MEI');
INSERT INTO public.section (id, public_id, description, label) VALUES (30,gen_random_uuid(),  'Seconde Professionnelle Métiers Relations Clients commune', '2MRC');
INSERT INTO public.section (id, public_id, description, label) VALUES (31,gen_random_uuid(),  'Troisième Prépa Métiers', '3PMET');
INSERT INTO public.section (id, public_id, description, label) VALUES (32,gen_random_uuid(),  'Terminale Générale – division1', 'TGA');
INSERT INTO public.section (id, public_id, description, label) VALUES (33,gen_random_uuid(),  'Terminale Générale – division2', 'TGB');
INSERT INTO public.section (id, public_id, description, label) VALUES (34,gen_random_uuid(),  'Terminale STI Développement Durable -Energie et Environnement(A)', 'TI2DA-EE');
INSERT INTO public.section (id, public_id, description, label) VALUES (35,gen_random_uuid(),  'Terminale STI Développement Durable - Innovation Technologique et Eco-Conception(B)', 'TI2DB-ITEC');
INSERT INTO public.section (id, public_id, description, label) VALUES (36,gen_random_uuid(),  'Terminale STI Développement Durable - Système d’Information et Numérique(C)', 'TI2DC-SIN');
INSERT INTO public.section (id, public_id, description, label) VALUES (37,gen_random_uuid(),  'Terminale Sciences et Technologies de la Santé et du Social -division 1', 'TSSS1');
INSERT INTO public.section (id, public_id, description, label) VALUES (38,gen_random_uuid(),  'Terminale Sciences et Technologies de la Santé et du Social -division 2', 'TSSS2');
INSERT INTO public.section (id, public_id, description, label) VALUES (39,gen_random_uuid(),  'Terminale STMG spécialité Ressources Humaines', 'TRH');
INSERT INTO public.section (id, public_id, description, label) VALUES (40,gen_random_uuid(),  'Terminale STMG spécialité Gestion et Finance', 'TGF');
INSERT INTO public.section (id, public_id, description, label) VALUES (41,gen_random_uuid(),  'Terminale STMG spécialité Mercatique (marketing)', 'TMC');
INSERT INTO public.section (id, public_id, description, label) VALUES (42,gen_random_uuid(),  'Première Générale – division1', '1GA');
INSERT INTO public.section (id, public_id, description, label) VALUES (43,gen_random_uuid(),  'Première Générale – division2', '1GB');
INSERT INTO public.section (id, public_id, description, label) VALUES (44,gen_random_uuid(),  'Première STI Développement Durable– division1', '1I2DA');
INSERT INTO public.section (id, public_id, description, label) VALUES (45,gen_random_uuid(),  'Première STI Développement Durable– division2', '1I2DB');
INSERT INTO public.section (id, public_id, description, label) VALUES (46,gen_random_uuid(),  'Première Sciences et Technologies de la Santé et du Social– division1', '1SSS1');
INSERT INTO public.section (id, public_id, description, label) VALUES (47,gen_random_uuid(),  'Première Sciences et Technologies de la Santé et du Social– division2', '1SSS2');
INSERT INTO public.section (id, public_id, description, label) VALUES (48,gen_random_uuid(),  'Première Sciences et Techniques du Management et de la Gestion-division 1', '1SG1');
INSERT INTO public.section (id, public_id, description, label) VALUES (49,gen_random_uuid(),  'Première Sciences et Techniques du Management et de la Gestion-division 2', '1SG2');
INSERT INTO public.section (id, public_id, description, label) VALUES (50,gen_random_uuid(),  'Seconde Générale et Technologique - division 1', '2GT1');
INSERT INTO public.section (id, public_id, description, label) VALUES (51,gen_random_uuid(),  'Seconde Générale et Technologique - division 2', '2GT2');
INSERT INTO public.section (id, public_id, description, label) VALUES (52,gen_random_uuid(),  'Seconde Générale et Technologique - division 3', '2GT3');
INSERT INTO public.section (id, public_id, description, label) VALUES (53,gen_random_uuid(),  'Seconde Générale et Technologique - division 4', '2GT4');
INSERT INTO public.section (id, public_id, description, label) VALUES (54,gen_random_uuid(),  'Seconde Générale et Technologique - division 5', '2GT5');
INSERT INTO public.section (id, public_id, description, label) VALUES (55,gen_random_uuid(),  'Classe Préparatoire des Métiers Sécurité Intérieure', 'PCMSI');
