INSERT INTO public.document_type (id, description, label, abr, scope) VALUES (1, 'Cerfa 15646*01', 'Autorisation de sortie du territoire (AST)', 'ast', 'TRIP');
INSERT INTO public.document_type (id, description, label, abr, scope) VALUES (2, null, 'Copie de la pièce d''identité du parent signataire de l''AST', 'ast_cni', 'TRIP');
INSERT INTO public.document_type (id, description, label, abr, scope) VALUES (3, 'Visa électronique pour le Canada', 'Autorisation eTA (arrivée par avion)', 'ca_eta', 'TRIP');
INSERT INTO public.document_type (id, description, label, abr, scope) VALUES (4, null, 'Carte Européenne d’Assurance Maladie', 'ceam', 'TRIP');
INSERT INTO public.document_type (id, description, label, abr, scope) VALUES (5, 'En cours de validité', 'Carte nationale d’identité', 'cni', 'GENERAL');
INSERT INTO public.document_type (id, description, label, abr, scope) VALUES (6, 'Visa électronique pour l''Égypte', 'Visa / e-Visa Égypte', 'eg_visa', 'TRIP');
INSERT INTO public.document_type (id, description, label, abr, scope) VALUES (7, null, 'Fiche sanitaire', 'health_form', 'GENERAL');
INSERT INTO public.document_type (id, description, label, abr, scope) VALUES (8, 'Visa électronique pour l''Indonésie', 'e-VOA / Visa à l’arrivée (preuve)', 'id_evoa', 'TRIP');
INSERT INTO public.document_type (id, description, label, abr, scope) VALUES (10, 'En cours de validité + 6 mois après la fin du voyage', 'Passeport', 'passport', 'GENERAL');
INSERT INTO public.document_type (id, description, label, abr, scope) VALUES (11, 'Visa électronique pour les USA', 'Autorisation ESTA', 'us_esta', 'TRIP');
INSERT INTO public.document_type (id, description, label, abr, scope) VALUES (12, 'Visa électronique pour le Royaume Uni', 'Autorisation eTA', 'uk_eta', 'TRIP');
INSERT INTO public.document_type (id, description, label, abr, scope) VALUES (9, null, 'Attestation d’assurance scolaire (RC + IA)', 'insurance', 'GENERAL');
