CREATE TABLE voyage_preferences
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    voyage_id BIGINT                                  NOT NULL,
    user_id   BIGINT                                  NOT NULL,
    interest  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_voyage_preferences PRIMARY KEY (id)
);

ALTER TABLE voyage_preferences
    ADD CONSTRAINT uc_032fa0846c7f6e915594f376d UNIQUE (voyage_id, user_id);

ALTER TABLE voyage_preferences
    ADD CONSTRAINT FK_VOYAGE_PREFERENCES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE voyage_preferences
    ADD CONSTRAINT FK_VOYAGE_PREFERENCES_ON_VOYAGE FOREIGN KEY (voyage_id) REFERENCES voyage (id);
