name: CI/CD - Spring Boot API (Docker + Compose)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write        # push vers GHCR
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Multi-arch optionnel : commente si inutile
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          build-args: |
            APP_VERSION=${{ github.sha }}

  deploy_to_server:
    runs-on: ubuntu-latest
    needs: build_and_push_image
    steps:
      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Pull & restart via Docker Compose
        env:
          DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}  # ex: /srv/myapp
          IMAGE: ghcr.io/${{ github.repository }}
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} && \
            cd ${DEPLOY_DIR} && \
            docker compose pull && \
            docker compose up -d && \
            docker image prune -f"

